version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-securepassword}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: always

  php:
    image: php:8.2-fpm
    container_name: php_app
    volumes:
      - ./src:/var/www/html
    networks:
      - app_network
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
